version: '3.5'
volumes:
  axia-ipcs:
services:
  mysql:
    image: "mysql:8.0.26"
    volumes:
      - /home/ubuntu/.magellan/mysql:/var/lib/mysql
      - ./../my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: magellan
    restart: on-failure
  migrate:
    image: "migrate/migrate:v4.14.1"
    volumes:
      - ../../services/db/migrations:/migrations
    depends_on:
      - mysql
    entrypoint: [ "/bin/sh" ]
    command: |
      -c 'while ! migrate -path=/migrations/ -database "mysql://root:password@tcp(mysql:3306)/magellan" up; do
        sleep 1
      done'
    restart: on-failure
  axia:
    env_file:
      - production.env
    image: "667299798306.dkr.ecr.us-east-1.amazonaws.com/axia-indexer-testnet-infra-axia59f2266c-mxatb6ymx02a:latest"
    command: /bin/sh -cx "exec /axia/build/axia --config-file=/opt/config.json --network-id=$${NETWORKID} "
    ports:
      - "9650:9650"
    volumes:
      - /home/ubuntu/.magellan/axia:/var/lib/axia
      - ./../axia_config.json:/opt/config.json
      - ./../axia_chain_config:/opt/axia
      - axia-ipcs:/tmp
    depends_on:
      - indexer
    restart: always
  indexer:
    &magellan-app
    image: "667299798306.dkr.ecr.us-east-1.amazonaws.com/axia-indexer-testnet-infra-magellan3ba08964-h5eca3o7tqfq:latest"
    command: [ "stream", "indexer", "-c", "/opt/config.json" ]
    external_links:
      - mysql
    depends_on:
      - mysql
      - migrate
    volumes:
      - axia-ipcs:/tmp
      - ./../config.json:/opt/config.json
    restart: on-failure
  api:
    <<: *magellan-app
    command: [ "api", "-c", "/opt/config.json" ]
    ports:
      - 8080:8080
