version: '3.5'
volumes:
  axia-ipcs:
services:
  mysql:
    image: "143953102251.dkr.ecr.us-east-1.amazonaws.com/axia-indexer-testnet-infra-mysql5168b53f-vmuhdp4dbwah:latest"
    volumes:
      - /home/ubuntu/.magellan/mysql:/var/lib/mysql
      - ./../my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: magellan
    restart: on-failure
  migrate:
    image: "143953102251.dkr.ecr.us-east-1.amazonaws.com/axia-indexer-testnet-infra-migrateed724f89-bs8x5rromfxv:latest"
    volumes:
      - ../../services/db/migrations:/migrations
    depends_on:
      - mysql
    entrypoint: ["/bin/sh"]
    command: |
      -c 'while ! migrate -path=/migrations/ -database "mysql://root:password@tcp(mysql:3306)/magellan" up; do
        sleep 1
      done'
    restart: on-failure
  axia:
    env_file:
      - production.env
    image: "143953102251.dkr.ecr.us-east-1.amazonaws.com/axia-indexer-testnet-infra-axia59f2266c-ogoxxo9ydchm:latest"
    command: /bin/sh -cx "exec /axia/build/axia
      --config-file=/opt/config.json
      --network-id=$${NETWORKID}
      "
    ports:
      - "9650:9650"
    volumes:
      - /home/ubuntu/.magellan/axia:/var/lib/axia
      - ./../axia_config.json:/opt/config.json
      - ./../axia_chain_config:/opt/axia
      - axia-ipcs:/tmp
    depends_on:
      - indexer
    restart: always
  indexer: &magellan-app
    image: "143953102251.dkr.ecr.us-east-1.amazonaws.com/axia-indexer-testnet-infra-magellan3ba08964-vnpvsc8ycc84:latest"
    command: ["stream", "indexer", "-c", "/opt/config.json"]
    external_links:
      - mysql
    depends_on:
      - mysql
      - migrate
    volumes:
      - axia-ipcs:/tmp
      - ./../config.json:/opt/config.json
    restart: on-failure
  api:
    <<: *magellan-app
    command: ["api", "-c", "/opt/config.json"]
    ports:
      - 8080:8080
  phpmyadmin:
    depends_on:
      - mysql
    image: "143953102251.dkr.ecr.us-east-1.amazonaws.com/axia-indexer-testnet-infra-phpmyadminf1f95b88-qxxtocp43hjl:latest"
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
